//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;
var en_ttypes = require('./en_types')
var core_ttypes = require('./core_types')


var ttypes = module.exports = {};
if (typeof thrift === 'undefined') {
  thrift = {};
}
if (typeof thrift.en === 'undefined') {
  thrift.en = {};
}
if (typeof thrift.en.emitir === 'undefined') {
  thrift.en.emitir = {};
}
