//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;
var en_ttypes = require('./en_types')
var core_ttypes = require('./core_types')


var ttypes = require('./emitir_types');
//HELPER FUNCTIONS AND STRUCTURES

thrift.en.emitir.SendService_send_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined) {
      this.request = args.request;
    }
  }
};
thrift.en.emitir.SendService_send_args.prototype = {};
thrift.en.emitir.SendService_send_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.request = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

thrift.en.emitir.SendService_send_args.prototype.write = function(output) {
  output.writeStructBegin('SendService_send_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRING, 1);
    output.writeString(this.request);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

thrift.en.emitir.SendService_send_result = function(args) {
  this.success = null;
  this.e = null;
  if (args instanceof core_ttypes.Exception) {
    this.e = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.e !== undefined) {
      this.e = args.e;
    }
  }
};
thrift.en.emitir.SendService_send_result.prototype = {};
thrift.en.emitir.SendService_send_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.e = new core_ttypes.Exception();
        this.e.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

thrift.en.emitir.SendService_send_result.prototype.write = function(output) {
  output.writeStructBegin('SendService_send_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  if (this.e !== null && this.e !== undefined) {
    output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
    this.e.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

thrift.en.emitir.SendServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
thrift.en.emitir.SendServiceClient.prototype = {};
thrift.en.emitir.SendServiceClient.prototype.send = function(request, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_send(request);
};

thrift.en.emitir.SendServiceClient.prototype.send_send = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('send', Thrift.MessageType.CALL, this.seqid);
  var args = new thrift.en.emitir.SendService_send_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

thrift.en.emitir.SendServiceClient.prototype.recv_send = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new thrift.en.emitir.SendService_send_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.e) {
    return callback(result.e);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('send failed: unknown result');
};
thrift.en.emitir.SendServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
thrift.en.emitir.SendServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

thrift.en.emitir.SendServiceProcessor.prototype.process_send = function(seqid, input, output) {
  var args = new thrift.en.emitir.SendService_send_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.send(args.request, function (err, result) {
    var result = new thrift.en.emitir.SendService_send_result((err != null ? err : {success: result}));
    output.writeMessageBegin("send", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

